//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 05:45:55 PM ADT 
//


package ca.unbsj.cbakerlab.sqltemplate.querymanager.sail.query_manager.predicate_views.parser.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sail.query_manager.predicate_views.parser.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PredicateViewsTestText_QNAME = new QName("", "text");
    private final static QName _PredicateViewsTestParameter_QNAME = new QName("", "parameter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sail.query_manager.predicate_views.parser.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PredicateViews.View.Query }
     * 
     */
    public PredicateViews.View.Query createPredicateViewsViewQuery() {
        return new PredicateViews.View.Query();
    }

    /**
     * Create an instance of {@link PredicateViews.View }
     * 
     */
    public PredicateViews.View createPredicateViewsView() {
        return new PredicateViews.View();
    }

    /**
     * Create an instance of {@link PredicateViews.Test }
     * 
     */
    public PredicateViews.Test createPredicateViewsTest() {
        return new PredicateViews.Test();
    }

    /**
     * Create an instance of {@link PredicateViews }
     * 
     */
    public PredicateViews createPredicateViews() {
        return new PredicateViews();
    }

    /**
     * Create an instance of {@link PredicateViews.View.Table }
     * 
     */
    public PredicateViews.View.Table createPredicateViewsViewTable() {
        return new PredicateViews.View.Table();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text", scope = PredicateViews.Test.class)
    public JAXBElement<String> createPredicateViewsTestText(String value) {
        return new JAXBElement<String>(_PredicateViewsTestText_QNAME, String.class, PredicateViews.Test.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parameter", scope = PredicateViews.Test.class)
    public JAXBElement<String> createPredicateViewsTestParameter(String value) {
        return new JAXBElement<String>(_PredicateViewsTestParameter_QNAME, String.class, PredicateViews.Test.class, value);
    }

}
