//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 05:45:55 PM ADT 
//


package ca.unbsj.cbakerlab.sqltemplate.querymanager.sail.query_manager.predicate_views.parser.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}TopLevelDeclaration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "topLevelDeclaration"
})
@XmlRootElement(name = "predicateViews")
public class PredicateViews {

    @XmlElements({
        @XmlElement(name = "view", type = PredicateViews.View.class),
        @XmlElement(name = "test", type = PredicateViews.Test.class)
    })
    protected List<Object> topLevelDeclaration;

    /**
     * Gets the value of the topLevelDeclaration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the topLevelDeclaration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopLevelDeclaration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PredicateViews.View }
     * {@link PredicateViews.Test }
     * 
     * 
     */
    public List<Object> getTopLevelDeclaration() {
        if (topLevelDeclaration == null) {
            topLevelDeclaration = new ArrayList<Object>();
        }
        return this.topLevelDeclaration;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}TemplateElement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="predicateName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="arity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "templateElement"
    })
    public static class Test {

        @XmlElementRefs({
            @XmlElementRef(name = "text", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "parameter", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<String>> templateElement;
        @XmlAttribute(required = true)
        protected String predicateName;
        @XmlAttribute(required = true)
        protected BigInteger arity;

        /**
         * Gets the value of the templateElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the templateElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTemplateElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getTemplateElement() {
            if (templateElement == null) {
                templateElement = new ArrayList<JAXBElement<String>>();
            }
            return this.templateElement;
        }

        /**
         * Gets the value of the predicateName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredicateName() {
            return predicateName;
        }

        /**
         * Sets the value of the predicateName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredicateName(String value) {
            this.predicateName = value;
        }

        /**
         * Gets the value of the arity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArity() {
            return arity;
        }

        /**
         * Sets the value of the arity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArity(BigInteger value) {
            this.arity = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}UnionMember" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="predicateName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="arity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unionMember"
    })
    public static class View {

        @XmlElements({
            @XmlElement(name = "table", type = PredicateViews.View.Table.class),
            @XmlElement(name = "query", type = PredicateViews.View.Query.class)
        })
        protected List<Object> unionMember;
        @XmlAttribute(required = true)
        protected String predicateName;
        @XmlAttribute(required = true)
        protected BigInteger arity;

        /**
         * Gets the value of the unionMember property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unionMember property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnionMember().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PredicateViews.View.Table }
         * {@link PredicateViews.View.Query }
         * 
         * 
         */
        public List<Object> getUnionMember() {
            if (unionMember == null) {
                unionMember = new ArrayList<Object>();
            }
            return this.unionMember;
        }

        /**
         * Gets the value of the predicateName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPredicateName() {
            return predicateName;
        }

        /**
         * Sets the value of the predicateName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPredicateName(String value) {
            this.predicateName = value;
        }

        /**
         * Gets the value of the arity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArity() {
            return arity;
        }

        /**
         * Sets the value of the arity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArity(BigInteger value) {
            this.arity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="body" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="exportedAttribute" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "body",
            "exportedAttribute"
        })
        public static class Query {

            @XmlElement(required = true)
            protected String body;
            @XmlElement(required = true)
            protected List<String> exportedAttribute;

            /**
             * Gets the value of the body property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBody() {
                return body;
            }

            /**
             * Sets the value of the body property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBody(String value) {
                this.body = value;
            }

            /**
             * Gets the value of the exportedAttribute property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the exportedAttribute property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExportedAttribute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getExportedAttribute() {
                if (exportedAttribute == null) {
                    exportedAttribute = new ArrayList<String>();
                }
                return this.exportedAttribute;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="exportedAttribute" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "exportedAttribute"
        })
        public static class Table {

            @XmlElement(required = true)
            protected List<String> exportedAttribute;
            @XmlAttribute(required = true)
            protected String name;

            /**
             * Gets the value of the exportedAttribute property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the exportedAttribute property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExportedAttribute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getExportedAttribute() {
                if (exportedAttribute == null) {
                    exportedAttribute = new ArrayList<String>();
                }
                return this.exportedAttribute;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
